### ISSUE TITLE
Have slash-command-dispatch respond with link to the action url

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/delivery-aws-iac#135]
This would be a nice QOL improvement.
It will respond with the job after it's completed.

https://github.com/peter-evans/slash-command-dispatch#responding-to-the-comment-on-command-completion

```yaml
      - name: Create URL to the run output
        id: vars
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}
```
